import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Body from "../components/Body";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Akkiei</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        <Header />
      </h1>
      <Body />

      <footer className={styles.footer}>
        <span className={styles.logo}>
          <Footer />
          {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
        </span>
      </footer>
    </div>
  );
}
